version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "applyStones"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hhwq1sj4w5y7"
s3_prefix = "applyStones"
region = "us-east-2"
profile = "default"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
