name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run:  echo "same build"

  prod-approval:
    runs-on: ubuntu-latest
    outputs:
     approved: ${{ steps.approval.outputs.approved }}
    steps:
      - name: Request approval for production deployment
        id: approval
        uses: sharan2717/approve-action@v1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-prod:
    runs-on: ubuntu-latest
    needs: prod-approval
    if: ${{ needs.prod-approval.outputs.approved == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: echo "Deploying to production environment..."
