name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to deploy to'
        required: true
        default: 'production'
      tag:
        description: 'Tag to deploy'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print inputs
      run: |
        echo "Environment: ${{ github.event.inputs.environment }}"
        echo "Tag: ${{ github.event.inputs.tag }}"

  call_another:
    uses: ./.github/workflows/call.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      tag: ${{ github.event.inputs.tag }}
