name: CI/CD Pipeline

on:
   pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Build project
        run: echo "sample build"

  request-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Approval step
        run: echo "Requesting approval for production deployment..."

  deploy-prod:
    runs-on: ubuntu-latest
    needs: request-approval
    environment:
      name: production
    steps:
      - name: Deploy to Production
        run: echo "Deploying to production environment..."
