name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run:  echo "sample build"

  prod-approval:
    runs-on: ubuntu-latest
    outputs:
     approved: ${{ steps.approval.outputs.approved }}
    steps:
      - name: Request approval for production deployment
        id: approval
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: 1
  deploy-prod:
    runs-on: ubuntu-latest
    needs: prod-approval
    if: ${{ needs.prod-approval.outputs.approved == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: echo "Deploying to production environment..."
